//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caps2CtrlSpace.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caps2CtrlSpace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1028_1_ {
            get {
                object obj = ResourceManager.GetObject("_1028_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1028_2_ {
            get {
                object obj = ResourceManager.GetObject("_1028_2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1028_3_ {
            get {
                object obj = ResourceManager.GetObject("_1028_3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1028_4_ {
            get {
                object obj = ResourceManager.GetObject("_1028_4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2052_0_ {
            get {
                object obj = ResourceManager.GetObject("_2052_0_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Check IME Mode (Will increase CPU usage) 的本地化字符串。
        /// </summary>
        internal static string strAutoCheckImeMode {
            get {
                return ResourceManager.GetString("strAutoCheckImeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Run Application When Windows Startup 的本地化字符串。
        /// </summary>
        internal static string strAutoRun {
            get {
                return ResourceManager.GetString("strAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled CapsLock Indicator Light (If Available) 的本地化字符串。
        /// </summary>
        internal static string strCapsState {
            get {
                return ResourceManager.GetString("strCapsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always On Top 的本地化字符串。
        /// </summary>
        internal static string strOnTop {
            get {
                return ResourceManager.GetString("strOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string strOptions {
            get {
                return ResourceManager.GetString("strOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Input Disabled Icon 的本地化字符串。
        /// </summary>
        internal static string strSaveAsImeModeDisabled {
            get {
                return ResourceManager.GetString("strSaveAsImeModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Input English Icon 的本地化字符串。
        /// </summary>
        internal static string strSaveAsImeModeEnglish {
            get {
                return ResourceManager.GetString("strSaveAsImeModeEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Input Locale Icon 的本地化字符串。
        /// </summary>
        internal static string strSaveAsImeModeLocale {
            get {
                return ResourceManager.GetString("strSaveAsImeModeLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Input Manual Icon 的本地化字符串。
        /// </summary>
        internal static string strSaveAsImeModeManual {
            get {
                return ResourceManager.GetString("strSaveAsImeModeManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Input Layout Indicator Icon 的本地化字符串。
        /// </summary>
        internal static string strSaveAsInputIndicator {
            get {
                return ResourceManager.GetString("strSaveAsInputIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert CapsLock key to Ctrl+Space 的本地化字符串。
        /// </summary>
        internal static string strTitleLong {
            get {
                return ResourceManager.GetString("strTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CapsLock To Ctrl+Space 的本地化字符串。
        /// </summary>
        internal static string strTitleShort {
            get {
                return ResourceManager.GetString("strTitleShort", resourceCulture);
            }
        }
    }
}
